### PR TITLE
Fixed blue rat name

### LINKED ISSUE #137: Rat pouch bug
The blue rat's name inside rat pouches displays the ID of blue rats instead of the name blue rat. This seems to be only for blue rats (maby golden i havent gotten one yet) and applies to all the pouches.
image

### PR DESCRIPTION
**Pull request by rob-katt**
Resolves #137

### CODE REVIEW

**Review by Pyrofab — APPROVED** [review]
Good catch

**Comment by Pyrofab** [comment]
Maybe you can fix the other localizations while you are at it ?

**Comment by rob-katt** [comment]
You mean removing the old and unused names?

**Comment by Pyrofab** [comment]
Well maybe if there are some, but I was more thinking of the other language files

**Comment by rob-katt** [comment]
I didnt find any other language files. I might just be blind

**Comment by Pyrofab** [comment]
Huh, true. I guess they were all deleted for 2.0.

**Comment by rob-katt** [comment]
I also noticed that remy didnt have a translation and that Jorato, Hollow, Rateline and Arathain are no longer in the game, so i fixed those to

**Comment by Pyrofab** [comment]
Sounds good to me

**Pull request merged**
